; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-stickc-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_58A6148585-if00
monitor_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_58A6148585-if00
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D USE_NIMBLE
lib_deps =
	m5stack/M5Unified @ ^0.2.13
	t-vk/ESP32 BLE Keyboard @ ^0.3.2
	h2zero/NimBLE-Arduino @ ^1.4.3
	crankyoldgit/IRremoteESP8266 @ ^2.8.6
